### ISSUE TITLE
TDF2016

### ISSUE THREAD

**Issue by triwats** [j0k3r/tourdefrance-slack-bot#3]
I'm assuming this will work without any modifications for TDF2016? :)

**Comment by j0k3r** [comment]
I guess it'll be as easy as the jump from 2014 to 2015: https://github.com/j0k3r/tourdefrance-slack-bot/commit/8bc99063490862e3541b90c1200ffa805fb18a9c

We'll see when the iPhone app will be updated: https://itunes.apple.com/fr/app/tour-de-france-2015/id537626279?mt=8

**Comment by triwats** [comment]
Great, looking forward to the start! 

Thanks again, great work.

**Comment by cuotos** [comment]
Intial checks seem to work, but I'm slightly confused on how stageMapsTable was originally populated?  Where did this data come from?

**Comment by j0k3r** [comment]
Sorry Dan I'm on vacation until mid-July  without computer and with a pretty unstable internet connection.

I'll try to check and remember how this variable has been populated.

**Comment by cuotos** [comment]
not a problem, I have been playing locally and replaced the images (route and profile) with the same ones that are provided on the letour website 

i.e. http://ww.letour.fr/PHOTOS/TDF/2016/100/PROFILE.png
http://ww.letour.fr/PHOTOS/TDF/2016/100/CARTE.jpg

**Comment by j0k3r** [comment]
Oh great!
Feel free to submit a PR about the 2016 edition and I'll do my best to merge it.

**Comment by j0k3r** [comment]
@cuotos any chance to submit a PR to allow the bot to work for the 2016 edition?

**Comment by cuotos** [comment]
To be honest, I have butchered the script quite a lot. I have just pushed a
version without keys etc to my fork. If you want me to raise a pull request
for the whole lot I can.
